services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: searchprop-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: searchprop-frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_BASE_URL: https://se-1f52a34cb4124c629a4aa7193d2377d6.ecs.ap-south-1.on.aws # update with backend url
    depends_on:
      - backend